
#ifndef LE_Transfer_TransferService_h
#define LE_Transfer_TransferService_h

#define TRANSFER_SERVICE_UUID_FLUSH           @"24E6E3F6-A3AB-4AC2-95EB-3BC51D75B650"
#define TRANSFER_SERVICE_UUID_SEAT           @"892F"


#define FLUSH_NIGHTLIGHT_ON_OFF @"1001"
#define FLUSH_FLUSH_ACTIVATION_LIGHT @"0004"
#define FLUSH_FLUSH_SENSOR @"0009"
#define FLUSH_FLUSH_SENSOR_DISTANCE @"0006"
#define FLUSH_NIGHTLIGHT_SCHEDULE @"1002"
#define MODEL @"2001"
#define SERIAL_NUMBER @"2002"
#define DEVICE_NAME @"2000"
#define NIGHTLIGHT_RGB @"1004"
#define NIGHTLIGHT_RGB_WHITE @"1004"
#define FLUSH_NIGHTLIGHT_RGB @"1003"
#define BATTERY_LEVEL @"0002"
#define INSTALL_DATE @"2003"
#define NIGHTLIGHT_RGB_PUREWARMTH @"1004"
#define FIRMWARE_VERSION @"2004"
#define RTC @"0001"
#define FLUSH @"0008"
#define FLUSH_CLEAN_MODE_TIME @"0007"
#define REMOVE_PRODUCT @"2008"
#define RESTORE_PRODUCT @"2006"
#define NIGHTLIGHT_BRIGHTNESS @"1002"
#define SEAT_SET_HEAT @"4000"
#define SEAT_SET_HEAT_VALUE @"4003"
#define SEAT_HEAT_SCHEDULE @"4002"
#define SEAT_HEAT_BRIGHTNESS @"1005"
#define SEAT_HEAT_TEMPERATURE @"4001"
#define SEAT_LIGHT_SCHEDULE @"1003"
#define FLUSH_TIMES @"0003"
#define SEAT_NIGHTLIGHT_ON_OFF @"1001"
#define SEAT_NIGHTLIGHT_SCHEDULE_ON_OFF @"1002"

#define BRIGHTNESS_LOW_VALUE @"33";
#define BRIGHTNESS_MED_VALUE @"99";
#define BRIGHTNESS_HIGH_VALUE @"FF";

#define ON_COMMAND @"01"
#define OFF_COMMAND @"00"
#define SENSOR_TWO_INCH_COMMAND @"00"
#define SENSOR_FOUR_INCH_COMMAND @"01"
#define SENSOR_SIX_INCH_COMMAND @"02"

#define SEAT_HEAT_OFF @"00"
#define SEAT_HEAT_LOW @"01"
#define SEAT_HEAT_MEDIUM @"02"
#define SEAT_HEAT_HIGH @"03"

//Color codes Seat
#define COLORCODE_DARK_PURPLE @"660099"
#define COLORCODE_WHITE @"FFFFFF"
#define COLORCODE_ORANGE1 @"F3F1ED"
#define COLORCODE_LIGHT_YELLOW @"F4F4E3"
#define COLORCODE_PINK1 @"E00747"
#define COLORCODE_PINK2 @"FF0093"
#define COLORCODE_GREEN1 @"15FF00"
#define COLORCODE_LIGHTBLUE1 @"71FBED"
#define COLORCODE_LIGHTBLUE2 @"A5DDE2"
#define COLORCODE_BLUE1 @"0DA4DE"
#define COLORCODE_DARKBLUE1 @"007BFF"
#define COLORCODE_VIOLET @"9900FF"

//Color codes Flush
#define COLORCODE_RELISHPINK @"E00046"
#define COLORCODE_ORANGE @"FF6900"
#define COLORCODE_YELLOW @"F6BE00"
#define COLORCODE_GREEN @"AADB1E"
#define COLORCODE_BLUE @"7AE1BF"
#define COLORCODE_LIGHT_BLUE @"9ADBE8"
#define COLORCODE_DARK_BLUE @"303AB2"
#define COLORCODE_SKY_BLUE @"00A5D5"
#define COLORCODE_PINK @"FF69B5"
#define COLORCODE_PURPLE @"963CBD"

#define DISCONNECTION_TEXT @"Your device is disconnected!!"

#define DEVICE_NAME_LENGTH 10

#endif

