 platform :ios, '12.0'

target 'TestTD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestTD
  
  pod 'SuneelTDKit', :path=> '../SuneelTDKit'

end
