platform :ios, '12.0'

target 'SuneelTDKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SuneelTDKit
pod 'DropDown'
pod 'LTSupportAutomotive', '~> 1.0'
end
